homeassistant:
  name: Home
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 252
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml

automation: !include automations.yaml
#binary_sensor: !include binary_sensor.yaml
#frontend: !include frontend.yaml
group: !include groups.yaml
#history_graph: !include history_graph.yaml
#input_boolean: !include input_boolean.yaml
#input_select: !include input_select.yaml
#input_text: !include input_text.yaml
#light: !include light.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
#switch: !include switch.yaml

arlo:
  username: !secret arlo_email
  password: !secret arlo_password

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
  - platform: generic
    still_image_url: !secret meteogram_png_url
    name: Forecast

cloud:

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Discover some devices automatically
discovery:

ffmpeg:

# Enables the frontend
frontend:

# Used for Google Calendar
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

hassio:

# Enables support for tracking state changes over time
history:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

hue:
  bridges:
    - host: !secret philips_hue_bridge

ifttt:
  key: !secret ifttt

# Show links to resources in log and frontend
introduction:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

notify:
  - platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

shopping_list:

# Track the sun
sun:

timer:
  5minutes:
    duration: '00:05:00'

# Text to speech
tts:
  - platform: google

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

