# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: BlackTower
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 252
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml

automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
#frontend: !include frontend.yaml
group: !include groups.yaml
#history_graph: !include history_graph.yaml
input_boolean: !include input_boolean.yaml
#input_select: !include input_select.yaml
#input_text: !include input_text.yaml
light: !include light.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml

arlo:
  username: !secret arlo_email
  password: !secret arlo_password

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
  - platform: generic
    still_image_url: !secret meteogram_png_url
    name: Forecast

# Discover some devices automatically
discovery:

ffmpeg:

# Used for Google Calendar
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

hue:
  bridges:
    - host: !secret philips_hue_bridge

ifttt:
  key: !secret ifttt

#nest:
#  client_id: !secret nest_id
#  client_secret: !secret nest_secret

recorder:
  purge_keep_days: 5
  db_url: !secret mariadb

shopping_list:

timer:
  5minutes:
    duration: '00:05:00'

# Text to speech
tts:
  - platform: google_translate

device_tracker:
  - platform: unifi_direct
    host: !secret unifi_ip
    username: !secret unifi_user
    password: !secret unifi_password

